[local]
localhost

[mongodb]
localhost ansible_connection=local

[catalogue]
localhost ansible_connection=local

[redis]
localhost ansible_connection=local

[user]
localhost ansible_connection=local

[cart]
localhost

[mysql]
localhost ansible_connection=local

[shipping]
localhost

[rabbitmq]
localhost ansible_connection=local

[payment]
localhost

[frontend]
localhost